name: "Upload to Azure Blob Storage"

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout code
      uses: actions/checkout@v4

    - name: Step 2 - Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Step 3 - Install dependencies
      run: |
        pip install azure-storage-blob

    - name: Step 4 - Export AZURE_STORAGE_ACCOUNT_KEY
      run: echo "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" >> $GITHUB_ENV

    - name: Step 5 - Run upload script
      run: python sas_token.py

    - name: Step 6 - Generate SAS Token
      run: bash generate_sas_token.sh

    - name: Step 7 - Use the SAS Token
      run: echo "The SAS URL is $SAS_URL"