name: "Upload to Azure Blob Storage"

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout code
      uses: actions/checkout@v4

    - name: Step 2 - Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Step 3 - Install dependencies
      run: pip install azure-storage-blob

    - name: Step 4 - Export AZURE_STORAGE_ACCOUNT_KEY
      run: echo "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" >> $GITHUB_ENV

    - name: Step 5 - Run upload script
      run: python sas_token.py

    # #   AZ CLI section
    # - name: Step 6 - Log in to Azure CLI
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CREDENTIALS }}

    # # - name: Step 6 - Log in to Azure using Managed Identity
    # #   run: az login --identity

    # - name: Step 7 - Generate SAS Token and Inject into GitHub
    #   run: bash generate_sas_token.sh

    # - name: Step 8 - Upload file using SAS URL
    #   run: python upload.py